name: Build G3A

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up fxSDK & gint
        uses: Lephenixnoir/setup-fxsdk@v1

      - name: Build G3A
        run: fxsdk build-cg

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: RMNChem-g3a
          path: "*.g3a"
